import type {
  BookMember,
  Category,
  LedgerBook,
  LedgerSnapshot,
  Transaction,
  TransactionShare,
} from "@/entities/ledger/types";

function isoAt(monthOffset: number, day: number, hour = 19, minute = 0) {
  const now = new Date();
  return new Date(
    now.getFullYear(),
    now.getMonth() + monthOffset,
    day,
    hour,
    minute,
    0,
  ).toISOString();
}

const book: LedgerBook = {
  id: "book-princess-q",
  name: "公主Q的账本",
  currency: "CNY",
  createdAt: isoAt(-5, 1, 9),
};

const members: BookMember[] = [
  {
    id: "member-qq",
    userId: "user-qq",
    displayName: "QQ",
    email: "qq@example.com",
    accentColor: "#355f45",
    role: "owner",
    joinedAt: isoAt(-5, 1, 9),
  },
  {
    id: "member-azhe",
    userId: "user-azhe",
    displayName: "阿哲",
    email: "azhe@example.com",
    accentColor: "#c26f49",
    role: "member",
    joinedAt: isoAt(-5, 2, 10),
  },
];

const categories: Category[] = [
  {
    id: "cat-food",
    bookId: null,
    name: "餐饮",
    type: "expense",
    icon: "UtensilsCrossed",
    color: "#f2c078",
    isSystem: true,
    createdAt: isoAt(-5, 1, 9),
  },
  {
    id: "cat-transport",
    bookId: null,
    name: "通勤",
    type: "expense",
    icon: "TramFront",
    color: "#6ea8a1",
    isSystem: true,
    createdAt: isoAt(-5, 1, 9),
  },
  {
    id: "cat-home",
    bookId: null,
    name: "家用",
    type: "expense",
    icon: "House",
    color: "#c8b17f",
    isSystem: true,
    createdAt: isoAt(-5, 1, 9),
  },
  {
    id: "cat-fun",
    bookId: null,
    name: "娱乐",
    type: "expense",
    icon: "Popcorn",
    color: "#d47f71",
    isSystem: true,
    createdAt: isoAt(-5, 1, 9),
  },
  {
    id: "cat-pet",
    bookId: null,
    name: "宠物",
    type: "expense",
    icon: "PawPrint",
    color: "#9a8dd8",
    isSystem: true,
    createdAt: isoAt(-5, 1, 9),
  },
  {
    id: "cat-salary",
    bookId: null,
    name: "工资",
    type: "income",
    icon: "Wallet",
    color: "#80a771",
    isSystem: true,
    createdAt: isoAt(-5, 1, 9),
  },
  {
    id: "cat-bonus",
    bookId: null,
    name: "奖金",
    type: "income",
    icon: "BadgeCent",
    color: "#6d9e61",
    isSystem: true,
    createdAt: isoAt(-5, 1, 9),
  },
  {
    id: "cat-settlement",
    bookId: null,
    name: "结算",
    type: "settlement",
    icon: "ArrowRightLeft",
    color: "#355f45",
    isSystem: true,
    createdAt: isoAt(-5, 1, 9),
  },
];

const transactions: Transaction[] = [
  {
    id: "txn-1",
    bookId: book.id,
    type: "expense",
    amount: 168,
    categoryId: "cat-food",
    payerMemberId: "member-qq",
    occurredAt: isoAt(0, 3, 19, 20),
    note: "晚餐和甜品",
    isShared: true,
    splitMethod: "equal",
    createdByMemberId: "member-qq",
    createdAt: isoAt(0, 3, 19, 22),
    updatedAt: isoAt(0, 3, 19, 22),
    deletedAt: null,
  },
  {
    id: "txn-2",
    bookId: book.id,
    type: "expense",
    amount: 96,
    categoryId: "cat-home",
    payerMemberId: "member-azhe",
    occurredAt: isoAt(0, 8, 20, 10),
    note: "超市补货",
    isShared: true,
    splitMethod: "equal",
    createdByMemberId: "member-azhe",
    createdAt: isoAt(0, 8, 20, 12),
    updatedAt: isoAt(0, 8, 20, 12),
    deletedAt: null,
  },
  {
    id: "txn-3",
    bookId: book.id,
    type: "expense",
    amount: 32,
    categoryId: "cat-food",
    payerMemberId: "member-qq",
    occurredAt: isoAt(0, 11, 8, 35),
    note: "早咖啡",
    isShared: false,
    splitMethod: "custom_amount",
    createdByMemberId: "member-qq",
    createdAt: isoAt(0, 11, 8, 40),
    updatedAt: isoAt(0, 11, 8, 40),
    deletedAt: null,
  },
  {
    id: "txn-4",
    bookId: book.id,
    type: "income",
    amount: 12000,
    categoryId: "cat-salary",
    payerMemberId: "member-qq",
    occurredAt: isoAt(0, 5, 9, 0),
    note: "本月工资",
    isShared: false,
    splitMethod: "custom_amount",
    createdByMemberId: "member-qq",
    createdAt: isoAt(0, 5, 9, 5),
    updatedAt: isoAt(0, 5, 9, 5),
    deletedAt: null,
  },
  {
    id: "txn-5",
    bookId: book.id,
    type: "expense",
    amount: 248,
    categoryId: "cat-fun",
    payerMemberId: "member-azhe",
    occurredAt: isoAt(-1, 18, 21, 10),
    note: "周末电影和夜宵",
    isShared: true,
    splitMethod: "equal",
    createdByMemberId: "member-azhe",
    createdAt: isoAt(-1, 18, 21, 15),
    updatedAt: isoAt(-1, 18, 21, 15),
    deletedAt: null,
  },
  {
    id: "txn-6",
    bookId: book.id,
    type: "expense",
    amount: 119,
    categoryId: "cat-pet",
    payerMemberId: "member-qq",
    occurredAt: isoAt(-2, 12, 18, 10),
    note: "猫砂和罐头",
    isShared: true,
    splitMethod: "equal",
    createdByMemberId: "member-qq",
    createdAt: isoAt(-2, 12, 18, 12),
    updatedAt: isoAt(-2, 12, 18, 12),
    deletedAt: null,
  },
];

const transactionShares: TransactionShare[] = [
  {
    id: "share-1",
    transactionId: "txn-1",
    memberId: "member-qq",
    shareAmount: 84,
    shareRatio: 0.5,
    isSettlementImpact: false,
  },
  {
    id: "share-2",
    transactionId: "txn-1",
    memberId: "member-azhe",
    shareAmount: 84,
    shareRatio: 0.5,
    isSettlementImpact: false,
  },
  {
    id: "share-3",
    transactionId: "txn-2",
    memberId: "member-qq",
    shareAmount: 48,
    shareRatio: 0.5,
    isSettlementImpact: false,
  },
  {
    id: "share-4",
    transactionId: "txn-2",
    memberId: "member-azhe",
    shareAmount: 48,
    shareRatio: 0.5,
    isSettlementImpact: false,
  },
  {
    id: "share-5",
    transactionId: "txn-3",
    memberId: "member-qq",
    shareAmount: 32,
    shareRatio: 1,
    isSettlementImpact: false,
  },
  {
    id: "share-6",
    transactionId: "txn-4",
    memberId: "member-qq",
    shareAmount: 12000,
    shareRatio: 1,
    isSettlementImpact: false,
  },
  {
    id: "share-7",
    transactionId: "txn-5",
    memberId: "member-qq",
    shareAmount: 124,
    shareRatio: 0.5,
    isSettlementImpact: false,
  },
  {
    id: "share-8",
    transactionId: "txn-5",
    memberId: "member-azhe",
    shareAmount: 124,
    shareRatio: 0.5,
    isSettlementImpact: false,
  },
  {
    id: "share-9",
    transactionId: "txn-6",
    memberId: "member-qq",
    shareAmount: 59.5,
    shareRatio: 0.5,
    isSettlementImpact: false,
  },
  {
    id: "share-10",
    transactionId: "txn-6",
    memberId: "member-azhe",
    shareAmount: 59.5,
    shareRatio: 0.5,
    isSettlementImpact: false,
  },
];

export function getDefaultLedgerSnapshot(): LedgerSnapshot {
  return {
    book,
    members,
    categories,
    transactions,
    transactionShares,
    invitations: [],
    preferences: {
      activeMemberId: "member-qq",
      themePreference: "system",
    },
  };
}
